# Generated by Django 3.2.14 on 2022-07-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('crop_rid', models.AutoField(primary_key=True, serialize=False)),
                ('crop_type', models.IntegerField()),
                ('crop_name', models.CharField(max_length=75)),
                ('crop_duration', models.IntegerField()),
                ('crop_image_url', models.ImageField(upload_to='crop/')),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('ds_rid', models.AutoField(primary_key=True, serialize=False)),
                ('ds_name', models.CharField(max_length=45)),
                ('ds_desc', models.CharField(max_length=500)),
                ('ds_control_methods', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='machines',
            fields=[
                ('mc_rid', models.AutoField(primary_key=True, serialize=False)),
                ('mc_id', models.CharField(max_length=45)),
                ('mc_name', models.CharField(max_length=45)),
                ('mc_price', models.IntegerField()),
                ('mc_contact', models.CharField(max_length=15)),
                ('mc_image_url', models.ImageField(upload_to='machines/')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('nw_rid', models.AutoField(primary_key=True, serialize=False)),
                ('nw_title', models.CharField(max_length=50)),
                ('nw_body', models.CharField(max_length=500)),
                ('nw_date_time', models.CharField(max_length=20)),
                ('nw_img_url', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('not_rid', models.AutoField(primary_key=True, serialize=False)),
                ('not_title', models.CharField(max_length=50)),
                ('not_body', models.CharField(max_length=500)),
                ('not_date_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='schemes',
            fields=[
                ('sc_rid', models.AutoField(primary_key=True, serialize=False)),
                ('sc_id', models.CharField(max_length=50)),
                ('sc_title', models.CharField(max_length=75)),
                ('sc_description', models.CharField(max_length=500)),
                ('sc_img_url', models.ImageField(upload_to='schemes/')),
                ('sc_date_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='symptom',
            fields=[
                ('sym_rid', models.AutoField(primary_key=True, serialize=False)),
                ('sym_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('u_rid', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('u_contact', models.CharField(max_length=15)),
                ('u_password', models.CharField(max_length=50)),
                ('u_email', models.CharField(max_length=50)),
                ('u_address', models.CharField(max_length=100)),
                ('u_pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='variety',
            fields=[
                ('vr_rid', models.AutoField(primary_key=True, serialize=False)),
                ('vr_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('vd_rid', models.AutoField(primary_key=True, serialize=False)),
                ('vd_title', models.CharField(max_length=75)),
                ('vd_thumbnail_url', models.ImageField(upload_to='video/')),
                ('vd_video_url', models.FileField(upload_to='video/')),
                ('vd_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weather',
            fields=[
                ('wt_rid', models.AutoField(primary_key=True, serialize=False)),
                ('wt_precipitation', models.IntegerField()),
                ('wt_humidity', models.IntegerField()),
                ('wt_wind', models.IntegerField()),
                ('wt_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('sell_rid', models.AutoField(primary_key=True, serialize=False)),
                ('sell_quantity', models.FloatField()),
                ('sell_unit_price', models.FloatField()),
                ('sell_total_price', models.FloatField()),
                ('sell_date', models.CharField(max_length=20)),
                ('sell_desc', models.CharField(max_length=500)),
                ('sell_crop_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.crop')),
                ('sell_user_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('pr_rid', models.AutoField(primary_key=True, serialize=False)),
                ('pr_price', models.IntegerField()),
                ('pr_updated_datetime', models.CharField(max_length=20)),
                ('pr_crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.crop')),
            ],
        ),
        migrations.CreateModel(
            name='disease_symptom_map',
            fields=[
                ('dsm_rid', models.AutoField(primary_key=True, serialize=False)),
                ('dsm_disease_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.disease')),
                ('dsm_symptom_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.disease'),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.variety'),
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('buy_rid', models.AutoField(primary_key=True, serialize=False)),
                ('buy_qty', models.FloatField()),
                ('buy_date', models.CharField(max_length=20)),
                ('buy_sell_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.sell')),
                ('buy_user_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmerFriendApp.user')),
            ],
        ),
    ]
